Repository grafana/tempo-operator, pull requests merged in 2023-03, with the labels that each got.

#305 Add docs for the supported storages
  docs/tempostack/object_storage.md
Labels: documentation

#283 Add support for Azure Storage
  apis/tempo/v1alpha1/storage.go
  apis/tempo/v1alpha1/tempostack_types.go
  apis/tempo/v1alpha1/tempostack_webhook.go
  apis/tempo/v1alpha1/tempostack_webhook_test.go
  bundle/manifests/tempo-operator.clusterserviceversion.yaml
  bundle/manifests/tempo.grafana.com_tempostacks.yaml
  cmd/generate/main.go
  cmd/generate/main_test.go
  config/crd/bases/tempo.grafana.com_tempostacks.yaml
  config/manifests/bases/tempo-operator.clusterserviceversion.yaml
  controllers/tempo/storage.go
  controllers/tempo/tempostack_controller.go
  controllers/tempo/tempostack_controller_test.go
  docs/operator/api.md
  internal/manifests/config/build.go
  internal/manifests/config/build_test.go
  internal/manifests/config/configmap.go
  internal/manifests/config/options.go
  internal/manifests/config/tempo-config.yaml
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  internal/manifests/manifestutils/params.go
  internal/manifests/manifestutils/storage.go
  internal/manifests/manifestutils/storage_test.go
Labels: enhancement

#325 Reload tenant configuration
  internal/manifests/gateway/gateway.go
Labels: go

#330 Reload tenant configuration
  internal/manifests/gateway/gateway.go
  internal/manifests/gateway/gateway_test.go
Labels: bug, go

#303 Add support for Google Cloud Storage
  apis/tempo/v1alpha1/storage.go
  apis/tempo/v1alpha1/tempostack_types.go
  bundle/manifests/tempo-operator.clusterserviceversion.yaml
  bundle/manifests/tempo.grafana.com_tempostacks.yaml
  cmd/generate/main.go
  cmd/generate/main_test.go
  config/crd/bases/tempo.grafana.com_tempostacks.yaml
  config/manifests/bases/tempo-operator.clusterserviceversion.yaml
  controllers/tempo/storage.go
  controllers/tempo/tempostack_controller.go
  docs/operator/api.md
  docs/tempostack/object_storage.md
  internal/manifests/config/build.go
  internal/manifests/config/build_test.go
  internal/manifests/config/configmap.go
  internal/manifests/config/options.go
  internal/manifests/config/tempo-config.yaml
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  internal/manifests/manifestutils/params.go
  internal/manifests/manifestutils/storage.go
  internal/manifests/manifestutils/storage_test.go
  main.go
  main_test.go
Labels: enhancement, go

#351 Use operator config from the openshift bundle for e2e tests
  kuttl-test-openshift.yaml
  tests/e2e-openshift/operator-config.yaml
Labels: Skip Changelog

#354 Fix changelog install make target
  Makefile
Labels: Skip Changelog

#356 Fix Makefile bundle rule
  Makefile
Labels: Skip Changelog

#364 Use Golang 1.20
  .github/workflows/continuous-integration.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scorecard.yaml
  Dockerfile
  go.mod
Labels: Skip Changelog
